"""
High-level actions for the slack module.

Used by fika-sync/workflow.csv:
  - publish_slack_summary  -> post_message
  - trigger_slack_command  -> parse_slash_command (RailCall receives
    the /fika-check webhook and passes the body to this function)
  - update_threshold       -> verify_slack_signature + parse_interactive_payload
    (when someone taps "Adjust my threshold")

**`post_message` has not been tested against a real Slack workspace
yet.** On the other hand, `verify_slack_signature`,
`parse_slash_command`, `parse_interactive_payload` and
`build_summary_blocks` are pure logic — no network calls — and can be
trusted just as much as `team-health-analyzer`'s, because they don't
depend on any assumption about a real HTTP response.

`verify_slack_signature` is, on top of that, the whole module's most
important security piece: without it, anyone could forge a click on
"Adjust my threshold" or a /fika-check.
"""

from __future__ import annotations

import hashlib
import hmac
import time
from typing import Optional
from urllib.parse import parse_qsl

from client import SlackClient

# Slack recommends rejecting requests older than 5 minutes to prevent
# replay attacks.
MAX_REQUEST_AGE_SECONDS = 60 * 5


# ---------------------------------------------------------------------------
# post_message (calls the real API)
# ---------------------------------------------------------------------------

def post_message(client: SlackClient, channel: str, text: str,
                  blocks: Optional[list] = None) -> dict:
    """Posts a message to a channel (POST chat.postMessage).

    `text` is always sent as a fallback (shown in push notifications
    and in clients that don't support Block Kit), even when `blocks`
    is also sent.
    """
    payload = {"channel": channel, "text": text}
    if blocks:
        payload["blocks"] = blocks
    return client.post("chat.postMessage", json_body=payload)


# ---------------------------------------------------------------------------
# build_summary_blocks (pure logic)
# ---------------------------------------------------------------------------

def build_summary_blocks(report_text: str, people: list) -> list:
    """Builds the Block Kit blocks for the weekly/daily summary.

    Adds an "Adjust my threshold" button for each person in `people`,
    with action_id="adjust_threshold" and value=person — so
    update_threshold knows whose click it is.

    Args:
        report_text: text already generated by
            team_health_analyzer.summarize_team_report.
        people: list of person names to show a button for.

    Returns:
        list of blocks in Block Kit format.
    """
    blocks = [
        {
            "type": "section",
            "text": {"type": "mrkdwn", "text": report_text},
        }
    ]

    if people:
        blocks.append({"type": "divider"})
        blocks.append({
            "type": "actions",
            "block_id": "adjust_threshold_actions",
            "elements": [
                {
                    "type": "button",
                    "text": {"type": "plain_text", "text": f"Adjust my threshold ({person})"},
                    "action_id": "adjust_threshold",
                    "value": person,
                }
                for person in people
            ],
        })

    return blocks


# ---------------------------------------------------------------------------
# verify_slack_signature (pure logic — security)
# ---------------------------------------------------------------------------

def verify_slack_signature(signing_secret: str, timestamp: str, raw_body: str,
                            signature: str, current_time: Optional[int] = None) -> bool:
    """Verifies that an incoming request genuinely came from Slack.

    Follows the algorithm documented by Slack
    (https://docs.slack.dev/authentication/verifying-requests-from-slack/):

        base_string = f"v0:{timestamp}:{raw_body}"
        signature   = "v0=" + HMAC-SHA256(signing_secret, base_string).hexdigest()

    Also rejects requests older than 5 minutes (protection against
    replay attacks), and uses constant-time comparison
    (`hmac.compare_digest`) to avoid timing attacks.

    Args:
        signing_secret: the Slack app's signing secret
            (SLACK_SIGNING_SECRET).
        timestamp: value of the X-Slack-Request-Timestamp header.
        raw_body: raw, unparsed request body.
        signature: value of the X-Slack-Signature header.
        current_time: current epoch in seconds; if not passed, uses
            time.time(). Parameterized so it can be tested without
            depending on the real clock.

    Returns:
        True if the signature is valid and the request isn't too old;
        False in any other case (including malformed timestamp or
        signature).
    """
    if current_time is None:
        current_time = int(time.time())

    try:
        request_time = int(timestamp)
    except (TypeError, ValueError):
        return False

    if abs(current_time - request_time) > MAX_REQUEST_AGE_SECONDS:
        return False

    base_string = f"v0:{timestamp}:{raw_body}"
    computed_hash = hmac.new(
        signing_secret.encode("utf-8"),
        base_string.encode("utf-8"),
        hashlib.sha256,
    ).hexdigest()
    computed_signature = f"v0={computed_hash}"

    return hmac.compare_digest(computed_signature, signature)


# ---------------------------------------------------------------------------
# parse_slash_command (pure logic)
# ---------------------------------------------------------------------------

def parse_slash_command(raw_body: str) -> dict:
    """Parses a slash command's body (/fika-check).

    Slack sends slash commands as application/x-www-form-urlencoded,
    not JSON. This function returns only the fields Fika Sync cares
    about.

    Args:
        raw_body: raw request body (form-urlencoded).

    Returns:
        dict with "command", "text", "user_id", "channel_id" (empty
        strings if a field wasn't present in the body).
    """
    fields = dict(parse_qsl(raw_body, keep_blank_values=True))
    return {
        "command": fields.get("command", ""),
        "text": fields.get("text", ""),
        "user_id": fields.get("user_id", ""),
        "channel_id": fields.get("channel_id", ""),
    }


# ---------------------------------------------------------------------------
# parse_interactive_payload (pure logic)
# ---------------------------------------------------------------------------

def parse_interactive_payload(raw_body: str) -> dict:
    """Parses a click on the "Adjust my threshold" button.

    Slack's interactivity payloads also arrive as form-urlencoded, but
    with a single `payload` field containing JSON. This function
    extracts the action_id, the value (the person) and who clicked
    from there.

    Args:
        raw_body: raw request body (form-urlencoded with a "payload"
            field in JSON).

    Returns:
        dict with "action_id", "person" (the button's value) and
        "clicked_by_user_id". If the payload has no action at all
        (rare case), "action_id" and "person" stay None.

    Raises:
        ValueError: if the body doesn't have a "payload" field or it
            isn't valid JSON.
    """
    import json

    fields = dict(parse_qsl(raw_body, keep_blank_values=True))
    payload_raw = fields.get("payload")
    if payload_raw is None:
        raise ValueError("The body doesn't have a 'payload' field.")

    payload = json.loads(payload_raw)

    actions = payload.get("actions", [])
    action_id = actions[0]["action_id"] if actions else None
    person = actions[0].get("value") if actions else None

    return {
        "action_id": action_id,
        "person": person,
        "clicked_by_user_id": payload.get("user", {}).get("id", ""),
    }
